### ISSUE TITLE
Needs a license

### ISSUE THREAD

**Issue by purpleidea** [jfontan/go-billy-desfacer#1]
Awesome work, thanks! For open source projects like https://github.com/purpleidea/mgmt/ to adopt this, it needs a license. Commonly I'd recommend LGPLv3+ or MIT or ALv2 for a small wrapper library like this. If you'd like help choosing, I'm happy to give you more tips. Thanks!!

**Comment by jfontan** [comment]
Thanks! I'm still in the process of adding missing interfaces and README. It will probably be apache, the same as `go-billy`.

So far only `Basic` and `Dir` are implemented:

```go
type Filesystem interface {
	Basic
	TempFile
	Dir
	Symlink
	Chroot
}
```

**Comment by purpleidea** [comment]
@jfontan Okay, awesome, no rush. In case you've already explored this area fuller, I'm trying to do: https://github.com/src-d/go-git/issues/1040
Hints welcome!
Cheers!

**Comment by purpleidea** [comment]
Thanks!

**Comment by jfontan** [comment]
I've also added an example on opening a repository in `_examples/go-git`. `Clone` is pretty similar.

**Comment by purpleidea** [comment]
@jfontan This is very helpful, thank you!
